application.id: documentservice-dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: mysql
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto=update: none

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml

  # Hibernate ddl auto (create, create-drop, validate, update)
logging:
  level:
    org:
      springframework:
        web: INFO
    com: DEBUG
